core/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

from .views import besta, HomeView, ListHomeView #HomeView

urlpatterns = [
    #path('', login_required(HomeView.as_view()), name='home'),
    path('', views.evento, name='home'),
    path('abra/', views.besta, name='todos_eventos'),
    path('<int:pk>/delete', views.evento_del, name='delete_evento'),
    path('l', views.evento_add, name='abra'),
    path('<int:pk>/update', views.evento_upd, name='update_evento'),
    path('<int:pk>/preview', views.evento_view, name='visualizar'),
    # path('3', login_required(HomeView.as_view()), name='home'),
    # path('4', login_required(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

# path('', login_required(v.list_produtos_page), name='produto_mp_list'),

fusion/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

app_name = 'site'  # começo da url

urlpatterns = [
    path('home/', login_required(views.PaginaInicial.as_view()), name='inicial'),
    path('contact/', login_required(views.ContactCreate.as_view()), name='contact'),
    path('service/detail/<int:pk>/', login_required(views.ServiceDetail.as_view()), name='service_detail'),
    path('resource/detail/<int:pk>/', login_required(views.ResourceDetail.as_view()), name='resource_detail'),
    path('team/detail/<int:pk>/', login_required(views.TeamDetail.as_view()), name='team_detail'),
    path('speech/detail/<int:pk>/', login_required(views.SpeechDetail.as_view()), name='speech_detail'),
    path('plan/detail/<int:pk>/', login_required(views.PlanDetail.as_view()), name='plan_detail'),
    path('phone/', login_required(views.PhoneList.as_view()), name='phone'),
    path('used/', login_required(views.Service_1.as_view()), name='used'),
]

luan_teste/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('class.urls')),
    path('accounts/', include('allauth.urls')),
    path('fusion/', include('fusion.urls')),
    path('htmx/', include('htmx.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fusion/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from .icons import ICONS_CHOICE


# Create your models here.
# class Fusion(models.Model):
#     servico = models.CharField(max_length=100)
#     titulo = models.CharField(max_length=100)
#     descricao = models.TextField(blank=True, null=True)
# data_tempo = models.DateTimeField(verbose_name='Data do Evento')
# data_dia = models.DateField(verbose_name='Data do Evento')
# salario = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
# habilitado = models.BooleanField(default=True, blank=True)
# data_criacao = models.DateTimeField(auto_now=True, verbose_name='Data de Criação')
# usuario = models.ForeignKey(User, on_delete=models.CASCADE) #relacionameto com outra tabela

# #  def __str__(self):
#       return self.titulo

class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    estado = models.CharField(max_length=100)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Empresa'  # nome para o cliente ver a (class 'Empresa')
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return f'{self.nome} | {self.cidade} - {self.estado}'


class Service(models.Model):
    STATUS_CHOICE = (
        ('active', 'Ativo'),
        ('deleted', 'Deletado'),
        ('blocked', 'Bloqueado'),
    )

    titulo = models.CharField('Titulo', max_length=100)
    descricao = models.TextField('Descrição', blank=True, null=True, )
    icone = models.CharField('Ícone', max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="services",
                                verbose_name='Empresa')  # relaciona o registro da tabela com o registro da tabela  Empresa
    liberado = models.BooleanField('Liberado', default=False)
    status = models.CharField('Status', choices=STATUS_CHOICE, default=STATUS_CHOICE[0][0], max_length=11, null=True, blank=True)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'

    def __str__(self):
        return str(self.pk) + ' ' + self.titulo + " " + self.descricao + " " + self.empresa.nome


class Resource(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    icone = models.CharField(max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE,
                                related_name="resources")  # relaciona o registro da tabela com o registro da tabela  Empresa

    class Meta:
        verbose_name = 'Recurso'
        verbose_name_plural = 'Recursos'

    def __str__(self):
        return self.titulo


class Team(models.Model):
    CARGOCHOICES = (
        ("1", "Area de programação"),
        ("2", "Area de direito"),
        ("3", "Area de diretoria"),
        ("4", "Area de almoxerifado"),
        ("5", "Area de farmácia"),
    )
    imagem = models.ImageField(blank=True, null=True, upload_to='team/')
    experiencia = models.DecimalField(max_digits=6, decimal_places=0, default=0)
    nome = models.CharField(max_length=100)
    cargo = models.CharField(choices=CARGOCHOICES, max_length=2)
    descricao = models.TextField(max_length=100)
    facebook_url = models.URLField(blank=True, null=True)
    twitter_url = models.URLField(blank=True, null=True)
    instagran_url = models.URLField(blank=True, null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="teams")

    class Meta:
        verbose_name = 'Equipe'
        verbose_name_plural = 'Equipes'

    def __str__(self):
        return self.nome


class Plan(models.Model):
    preco = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    titulo = models.TextField(max_length=100, blank=True, null=True)
    icone = models.CharField(max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="plans")

    class Meta:
        verbose_name = 'Plano'
        verbose_name_plural = 'Planos'

    def __str__(self):
        return str(self.preco)


class Speech(models.Model):
    imagem = models.ImageField(blank=True, null=True, upload_to='speech/')
    nome = models.TextField(max_length=100, blank=True, null=True)
    cargo = models.CharField(max_length=100)
    mensagem = models.TextField(max_length=100)
    nota = models.SmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    nota2 = models.PositiveSmallIntegerField(validators=[MaxValueValidator(5)], default=0)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="speechs")

    class Meta:
        verbose_name = 'Depoimento'
        verbose_name_plural = 'Depoimentos'

    def __str__(self):
        return str(self.nota)


class Contact(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    assunto = models.TextField(max_length=100)
    mensagem = models.TextField(max_length=100)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="contacts")

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.nome


class Phone(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    telefone = models.CharField(max_length=11, blank=True, null=True)

    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

    def __str__(self):
        return str(self.telefone)

templates/partials/contact.html
Seu formulario foi enviado com sucesso!!!

templates/partials/phone.html
{{object_list}}

templates/partials/plan.html
<div class="col-lg-4 col-md-6 col-xs-12">
    <div class="table wow fadeInLeft" data-wow-delay="1.2s">
        <div class="icon-box">
            <i class="{{plan.icone}}"></i>
        </div>
        <div class="pricing-header">
            <p class="price-value">{{plan.preco}}<span> /mo</span></p>
        </div>
        <div class="title">
            <h3>{{plan.titulo}}</h3>
        </div>
        <ul class="description">
            <li>{{plan.empresa}}</li>
            <!--            <li>10 GB storage</li>-->
            <!--            <li>Email support</li>-->
            <!--            <li>Lifetime updates</li>-->

        </ul>

        <a class="btn btn-common" href="{% url 'site:plan_detail' pk=plan.id %}"> Buy Now</a>
        <!--        <h2><a href="{% url 'site:plan_detail' pk=plan.id %}">{{plan.nome}}</a></h2>-->
    </div>
</div>

templates/partials/resource.html
<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
    <div class="content-left">
        <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
                <span class="icon">
                  <i class="{{ resource.icone }}"></i>
                </span>
                <div class="text  texto-preto">
                    <h3><a href="{% url 'site:resource_detail' pk=resource.id %}">{{ resource.titulo }}</a></h3>
                    <!--                <h4>{{ resource.titulo }}</h4>-->
                    <p>{{ resource.descricao }}</p>
            </div>
        </div>

    </div>
</div>

templates/partials/service.html
<!-- Services item -->
<div class="col-md-6 col-lg-4 col-xs-12">
    <div class="services-item wow fadeInRight" data-wow-delay="0.3s">
        <div class="icon">
            <i class="{{ service.icone }}"></i>
        </div>
        <div class="services-content">
            <h3><a href="{% url 'site:service_detail' pk=service.id %}">{{ service.titulo }}</a></h3>
            <p>{{ service.descricao }} </p>
        </div>
    </div>
</div>
<!-- Services item -->

templates/partials/service1.html
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 22.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg fill="#000000" width="52" height="52" version="1.1" id="lni_lni-android" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
	 y="0px" viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<g>
	<circle cx="26.6" cy="12.6" r="1.7"/>
	<circle cx="36.9" cy="12.6" r="1.7"/>
	<path d="M54.6,18.1c-0.8,0-1.6,0.2-2.4,0.5L52,18c-1.3-4-3.7-7.4-6.8-9.8l4.8-4.9c0.7-0.7,0.7-1.8,0-2.5c-0.7-0.7-1.8-0.7-2.5,0
		l-5,5.1c-0.1,0.1-0.1,0.2-0.2,0.2c-3-1.7-6.5-2.6-10.2-2.6c-3.6,0-7,0.9-10,2.5C22,6,22,5.9,21.9,5.9l-5-5.1
		c-0.7-0.7-1.8-0.7-2.5,0c-0.7,0.7-0.7,1.8,0,2.5L19.1,8c-3.2,2.5-5.6,5.9-6.9,9.9l-0.1,0.3c-0.8-0.4-1.7-0.6-2.7-0.6
		c-3.4,0-6.2,2.8-6.2,6.2v11.4c0,3.4,2.8,6.2,6.2,6.2c1,0,1.9-0.2,2.7-0.6v7.3c0,1.2,0.9,2.2,2.2,2.2h1.8v7.3c0,3.4,2.8,6.2,6.2,6.2
		c3.4,0,6.2-2.8,6.2-6.2v-7.3h6.2v7.3c0,3.4,2.8,6.2,6.2,6.2s6.2-2.8,6.2-6.2v-7.3h2.5c1.2,0,2.2-0.9,2.2-2.2v-6.9
		c0.8,0.4,1.7,0.6,2.7,0.6c3.4,0,6.2-2.8,6.2-6.2V24.3C60.8,20.9,58,18.1,54.6,18.1z M32.1,7c6.7,0,12.8,3.8,15.7,9.7H16.5
		C19.3,10.8,25.3,7,32.1,7z M9.4,38c-1.5,0-2.7-1.2-2.7-2.7V23.9c0-1.5,1.2-2.7,2.7-2.7s2.7,1.2,2.7,2.7v11.4
		C12.1,36.7,10.9,38,9.4,38z M25.1,57.5c0,1.5-1.2,2.7-2.7,2.7s-2.7-1.2-2.7-2.7v-7.3h5.4V57.5z M43.7,57.5c0,1.5-1.2,2.7-2.7,2.7
		s-2.7-1.2-2.7-2.7v-7.3h5.4V57.5z M48.4,46.8h-1.2h-1.9h-0.9h-9.6h-6.2h-9.5h-0.4h-2.6h-0.5V35.2V23.9v-3.6h32.7v4.1v11.4V46.8z
		 M57.3,35.7c0,1.5-1.2,2.7-2.7,2.7s-2.7-1.2-2.7-2.7V24.3c0-1.5,1.2-2.7,2.7-2.7s2.7,1.2,2.7,2.7V35.7z"/>
</g>
</svg>

templates/partials/speech.html
<div class="item">
    <div class="testimonial-item">
        <div class="img-thumb img-speech">
            <img src="{{ speech.imagem.url }}" alt="">
        </div>
        <div class="info">
            <h2><a href="{% url 'site:speech_detail' pk=speech.id %}">{{speech.nome}}</a></h2>
            <h3><a href="#">{{speech.cargo}}</a></h3>
        </div>
        <div class="content">
            <p class="description">{{speech.mensagem}}</p>
            <div class="star-icon mt-3">
                <span><i class="lni-star-{% if speech.nota > 0 %}filled{% else %}half{% endif %}"></i></span>
                <span><i class="lni-star-{% if speech.nota > 1 %}filled{% else %}half{% endif %}"></i></span>
                <span><i class="lni-star-{% if speech.nota > 2 %}filled{% else %}half{% endif %}"></i></span>
                <span><i class="lni-star-{% if speech.nota > 3 %}filled{% else %}half{% endif %}"></i></span>
                <span><i class="lni-star-{% if speech.nota > 4 %}filled{% else %}half{% endif %}"></i></span>
            </div>
        </div>
    </div>
</div>

templates/partials/team.html
<div class="col-lg-6 col-md-12 col-xs-12">
    <!-- Team Item Starts -->
    <div class="team-item wow fadeInRight" data-wow-delay="0.2s">
        <div class="team-img">
            <img class="img-fluid img-fix" src="{{ team.imagem.url }}" alt="">
        </div>
        <div class="contetn">
            <div class="info-text">
                <h3><a href="{% url 'site:team_detail' pk=team.id %}">{{team.nome}}</a></h3>
                <p>{{team.get_cargo_display}}</p>
            </div>
            <p>{{team.descricao}}.</p>
            <ul class="social-icons">
                <li><a href="{{team.facebook_url}}"><i class="lni-facebook-filled" aria-hidden="true"></i></a></li>
                <li><a href="{{team.twitter_url}}"><i class="lni-twitter-filled" aria-hidden="true"></i></a></li>
                <li><a href="{{team.instagran_url}}"><i class="lni-instagram-filled" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
    <!-- Team Item Ends -->
</div>