class/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

app_name = 'class' #começo da url

urlpatterns = [
    path('classlist/', views.ClienteList.as_view(), name='urls'),
    path('create/', views.ClienteCreate.as_view(), name='list_create'),
    path('detail/<int:pk>/', views.ClienteDetail.as_view(), name='list_detail'),
    path('delete/<int:pk>/', views.ClienteDelete.as_view(), name='list_delete'),
    path('update/<int:pk>/', views.ClienteUpdate.as_view(), name='list_update'),


 ]

core/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

from .views import besta, HomeView, ListHomeView #HomeView

urlpatterns = [
    #path('', login_required(HomeView.as_view()), name='home'),
    path('', views.evento, name='home'),
    path('abra/', views.besta, name='todos_eventos'),
    path('<int:pk>/delete', views.evento_del, name='delete_evento'),
    path('l', views.evento_add, name='abra'),
    path('<int:pk>/update', views.evento_upd, name='update_evento'),
    path('<int:pk>/preview', views.evento_view, name='visualizar'),
    # path('3', login_required(HomeView.as_view()), name='home'),
    # path('4', login_required(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

# path('', login_required(v.list_produtos_page), name='produto_mp_list'),

luan_teste/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('class.urls')),
    path('accounts/', include('allauth.urls')),
    path('fusion/', include('fusion.urls')),
    path('htmx/', include('htmx.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class/models.py
from django.contrib.auth.models import User
from django.db import models

#Create your models here.
class Cliente(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    data_evento = models.DateTimeField(verbose_name='Data do Evento')
    salario = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    habilitado = models.BooleanField(default=True, blank=True)
    data_criacao = models.DateTimeField(auto_now=True, verbose_name='Data de Criação')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

 # #  def __str__(self):
 #       return self.titulo

class/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        #fields = ['nome","data", 'habilitado']   #uma opção
        fields = '__all__'

class/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Cliente
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView, TemplateView


class ClienteList(ListView):
   model = Cliente
   #template_name ='cliente_list.html'
   paginate_by = 3

class ClienteCreate(CreateView):
   model = Cliente
   success_url = reverse_lazy ('class:urls')
  # template_name = 'create.html'
   fields = '__all__'

class ClienteDetail(DetailView):
   model = Cliente

class ClienteDelete(DeleteView):
   queryset = Cliente.objects.all()
   success_url = reverse_lazy('class:urls')

class ClienteUpdate(UpdateView):
   model = Cliente
   success_url = reverse_lazy('class:urls')
   #template_name = 'create.html'
   fields = '__all__'

templates/class/cliente_confirm_delete.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Apagar cliente</title>
</head>
<body>
Tem certeza que deseja apagar o cliente '{{ object.titulo }} '?
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="Sim, tenho certeza" >
    <input type="reset" onclick="location.href= '{% url 'class:urls' %}'" value="Não quero apagar" >
</form></body>
</html>

templates/class/cliente_detail.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vizualizar Cliente</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<input type="submit" onclick="location.href = '{% url 'class:urls' %}'" value="voltar">
<br/>
<br/>

Titulo: {{ object.titulo }}
    <p>Descrição: {{ object.descricao}}</p>
    <p>Data do Evento: {{ object.data_evento}}</p>
    <p>Salário: {{ object.salario}}</p>
    <p>Habilitado: {{ object.habilitado}}</p>
    <p>Data da Criação: {{ object.data_criacao}}</p>
    <p>Usuário: {{ object.usuario}}</p>

</body>
</html>

templates/class/cliente_form.html
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maimum-scale=1.0, minimum-scale=1.0>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Adcionando Clientes </title>
</head>
<body>

<h1>Cadastro de Clientes</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar" >
    <input type="reset" value="Cancelar" onclick="location.href = '{% url 'class:urls' %}'">


</form>
</body>

</html>

templates/class/cliente_in_list.html
<ul>
    <li><a href = "{% url 'class:list_detail' pk=cliente.id %}">Visualizar cliente<a/>--------------Titulo: {{ cliente.titulo }}
</li>
    <li><a href = "{% url 'class:list_delete' pk=cliente.id %}">Deletar cliente<a/>------------------{{ cliente.salario}}
</li>
    <li><a href = "{% url 'class:list_update' pk=cliente.id %}">Alterar cliente<a/>------------------{{ cliente.data_evento}}
</li>
    <li>-------------------------------------{{ cliente.descricao}}</li>
    <li>-------------------------------------{{ cliente.habilitado}}</li>
    <li>-------------------------------------{{ cliente.usuario}}</li>
    </ul>

templates/class/cliente_list.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <title>Lista de Clientes </title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maimum-scale=1.0, minimum-scale=1.0>
    <meta http-equiv="X-UA-Compatible content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <style>
   ul {
    list-style-type: circle;
    border-style: dashed;
    border-width: 3px;
<!--    border-left-width: 10px;-->
<!--    border-right-width: 10px;-->
    border-color: red;
}

</style>
</head>
<body>

<h1>Lista de Clientes</h1>
 <input type="submit" onclick="location.href = '{% url 'class:list_create' %}'" value="Criar novo cliente">

    {% for cliente in page_obj %}
    {% include 'class/cliente_in_list.html' %}
    {% endfor %}


    {% include 'pagination.html' %}

{{ page_obj.paginator.count }}
</body>

</html>