class/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

app_name = 'class' #começo da url

urlpatterns = [
    path('classlist/', views.ClienteList.as_view(), name='urls'),
    path('create/', views.ClienteCreate.as_view(), name='list_create'),
    path('detail/<int:pk>/', views.ClienteDetail.as_view(), name='list_detail'),
    path('delete/<int:pk>/', views.ClienteDelete.as_view(), name='list_delete'),
    path('update/<int:pk>/', views.ClienteUpdate.as_view(), name='list_update'),


 ]

core/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

from .views import besta, HomeView, ListHomeView #HomeView

urlpatterns = [
    #path('', login_required(HomeView.as_view()), name='home'),
    path('', views.evento, name='home'),
    path('abra/', views.besta, name='todos_eventos'),
    path('<int:pk>/delete', views.evento_del, name='delete_evento'),
    path('l', views.evento_add, name='abra'),
    path('<int:pk>/update', views.evento_upd, name='update_evento'),
    path('<int:pk>/preview', views.evento_view, name='visualizar'),
    # path('3', login_required(HomeView.as_view()), name='home'),
    # path('4', login_required(HomeView.as_view()), name='home'),
    # path('', HomeView.as_view(), name='home'),
]

# path('', login_required(v.list_produtos_page), name='produto_mp_list'),

fusion/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.checks import templates
from django.urls import include, path

app_name = 'site'  # começo da url

urlpatterns = [
    path('home/', login_required(views.PaginaInicial.as_view()), name='inicial'),
    path('contact/', login_required(views.ContactCreate.as_view()), name='contact'),
    path('service/detail/<int:pk>/', login_required(views.ServiceDetail.as_view()), name='service_detail'),
    path('resource/detail/<int:pk>/', login_required(views.ResourceDetail.as_view()), name='resource_detail'),
    path('team/detail/<int:pk>/', login_required(views.TeamDetail.as_view()), name='team_detail'),
    path('speech/detail/<int:pk>/', login_required(views.SpeechDetail.as_view()), name='speech_detail'),
    path('plan/detail/<int:pk>/', login_required(views.PlanDetail.as_view()), name='plan_detail'),
    path('phone/', login_required(views.PhoneList.as_view()), name='phone'),
    path('used/', login_required(views.Service_1.as_view()), name='used'),
]

luan_teste/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clientes/', include('class.urls')),
    path('accounts/', include('allauth.urls')),
    path('fusion/', include('fusion.urls')),
    path('htmx/', include('htmx.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fusion/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from .icons import ICONS_CHOICE


# Create your models here.
# class Fusion(models.Model):
#     servico = models.CharField(max_length=100)
#     titulo = models.CharField(max_length=100)
#     descricao = models.TextField(blank=True, null=True)
# data_tempo = models.DateTimeField(verbose_name='Data do Evento')
# data_dia = models.DateField(verbose_name='Data do Evento')
# salario = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
# habilitado = models.BooleanField(default=True, blank=True)
# data_criacao = models.DateTimeField(auto_now=True, verbose_name='Data de Criação')
# usuario = models.ForeignKey(User, on_delete=models.CASCADE) #relacionameto com outra tabela

# #  def __str__(self):
#       return self.titulo

class Empresa(models.Model):
    nome = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    estado = models.CharField(max_length=100)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Empresa'  # nome para o cliente ver a (class 'Empresa')
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return f'{self.nome} | {self.cidade} - {self.estado}'


class Service(models.Model):
    STATUS_CHOICE = (
        ('active', 'Ativo'),
        ('deleted', 'Deletado'),
        ('blocked', 'Bloqueado'),
    )

    titulo = models.CharField('Titulo', max_length=100)
    descricao = models.TextField('Descrição', blank=True, null=True, )
    icone = models.CharField('Ícone', max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="services",
                                verbose_name='Empresa')  # relaciona o registro da tabela com o registro da tabela  Empresa
    liberado = models.BooleanField('Liberado', default=False)
    status = models.CharField('Status', choices=STATUS_CHOICE, default=STATUS_CHOICE[0][0], max_length=11, null=True, blank=True)

    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'

    def __str__(self):
        return str(self.pk) + ' ' + self.titulo + " " + self.descricao + " " + self.empresa.nome


class Resource(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    icone = models.CharField(max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE,
                                related_name="resources")  # relaciona o registro da tabela com o registro da tabela  Empresa

    class Meta:
        verbose_name = 'Recurso'
        verbose_name_plural = 'Recursos'

    def __str__(self):
        return self.titulo


class Team(models.Model):
    CARGOCHOICES = (
        ("1", "Area de programação"),
        ("2", "Area de direito"),
        ("3", "Area de diretoria"),
        ("4", "Area de almoxerifado"),
        ("5", "Area de farmácia"),
    )
    imagem = models.ImageField(blank=True, null=True, upload_to='team/')
    experiencia = models.DecimalField(max_digits=6, decimal_places=0, default=0)
    nome = models.CharField(max_length=100)
    cargo = models.CharField(choices=CARGOCHOICES, max_length=2)
    descricao = models.TextField(max_length=100)
    facebook_url = models.URLField(blank=True, null=True)
    twitter_url = models.URLField(blank=True, null=True)
    instagran_url = models.URLField(blank=True, null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="teams")

    class Meta:
        verbose_name = 'Equipe'
        verbose_name_plural = 'Equipes'

    def __str__(self):
        return self.nome


class Plan(models.Model):
    preco = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    titulo = models.TextField(max_length=100, blank=True, null=True)
    icone = models.CharField(max_length=100, choices=ICONS_CHOICE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="plans")

    class Meta:
        verbose_name = 'Plano'
        verbose_name_plural = 'Planos'

    def __str__(self):
        return str(self.preco)


class Speech(models.Model):
    imagem = models.ImageField(blank=True, null=True, upload_to='speech/')
    nome = models.TextField(max_length=100, blank=True, null=True)
    cargo = models.CharField(max_length=100)
    mensagem = models.TextField(max_length=100)
    nota = models.SmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    nota2 = models.PositiveSmallIntegerField(validators=[MaxValueValidator(5)], default=0)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="speechs")

    class Meta:
        verbose_name = 'Depoimento'
        verbose_name_plural = 'Depoimentos'

    def __str__(self):
        return str(self.nota)


class Contact(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    assunto = models.TextField(max_length=100)
    mensagem = models.TextField(max_length=100)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="contacts")

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.nome


class Phone(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    telefone = models.CharField(max_length=11, blank=True, null=True)

    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

    def __str__(self):
        return str(self.telefone)

fusion/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        #fields = ['nome","data", 'habilitado']   #uma opção
        #fields = '__all__'
        exclude = ["empresa"]

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nome','data-error':"Por favor digite seu nome", 'required':'requirid'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Email','data-error':"Por favor digite seu email", 'required':'requirid'}),
            'assunto': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Assunto','data-error':"Por favor digite um assunto", 'required':'requirid'}),
            'mensagem': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Sua mensagem','data-error':"Por favor digite uma mensagem", 'required':'requirid'}),


        }

fusion/views.py
import random

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, CreateView, DetailView, ListView
from .models import Service, Resource, Team, Plan, Speech, Contact, Phone
from .forms import ContactForm


@method_decorator(csrf_exempt, name='dispatch')
class PaginaInicial(TemplateView):
    template_name = 'fusion.html'

    # def post(self, *args,**kwargs):
    #     print(dir(self.request.POST.values()))
    #     print(list(self.request.POST.values()))
    #     return HttpResponse(status=200,content="recebido")

    def get_context_data(self, **kwargs):
        # print(self.request.POST)
        sel_experiencia = self.request.GET.get("experiencia",0)
        user = self.request.user
        empresa = user.empresa
        context = super(PaginaInicial, self).get_context_data()
        services = Service.objects.filter(empresa=empresa)
        context["services"] = services
        #            resources = Resource.objects.all()
        #            context["resources"] = resources
        resources = Resource.objects.filter(empresa=empresa)
        context["resources"] = resources
        #            teams = Team.objects.all()
        #            context["teams"] = teams
        teams = Team.objects.filter(empresa=empresa, experiencia__gte=sel_experiencia)
        context["teams"] = teams
        plans = Plan.objects.filter(empresa=empresa)
        context["plans"] = plans
        speechs = Speech.objects.filter(empresa=empresa)
        context["speechs"] = speechs
        form = ContactForm
        context["form"] = form
        context["sel_experiencia"] = sel_experiencia
        # context["tola"] = "god"
        # context["berinha"] = random.randint(5,15)
        return context


class Service_1(TemplateView):
    template_name = 'partials/service1.html'

class ContactCreate(CreateView):
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('site:contact')
    template_name = 'partials/contact.html'

    # fields = '__all__'

    def form_valid(self, form):
        user = self.request.user
        empresa = user.empresa
        form.instance.empresa = empresa
        return super().form_valid(form)


class ServiceDetail(DetailView):
    model = Service
    template_name = 'details/service_detail.html'

    def get(self, request, *args, **kwargs):
        usuario = request.user
        service = self.get_object()
        usuario_service = service.empresa.usuario

        if usuario != usuario_service:
            return HttpResponse(status=401, content="Voce não tem acesso a esse produto")
        return super().get(self, request, *args, **kwargs)


class ResourceDetail(DetailView):
    model = Resource
    template_name = 'details/resource_detail.html'

    def get(self, request, *args, **kwargs):
        usuario = request.user
        resource = self.get_object()
        usuario_resource = resource.empresa.usuario

        if usuario != usuario_resource:
            return HttpResponse(status=401, content="Voce não tem acesso a esse produto")
        return super().get(self, request, *args, **kwargs)


class TeamDetail(DetailView):
    model = Team
    template_name = 'details/team_detail.html'

    def get(self, request, *args, **kwargs):
        usuario = request.user
        team = self.get_object()
        usuario_team = team.empresa.usuario

        if usuario != usuario_team:
            return HttpResponse(status=401, content="Voce não tem acesso a essa conta")
        return super().get(self, request, *args, **kwargs)


class SpeechDetail(DetailView):
    model = Speech
    template_name = 'details/speech_detail.html'

    def get(self, request, *args, **kwargs):
        usuario = request.user
        speech = self.get_object()
        usuario_speech = speech.empresa.usuario

        if usuario != usuario_speech:
            return HttpResponse(status=401, content="Voce não tem acesso a essa conta")
        return super().get(self, request, *args, **kwargs)


class PlanDetail(DetailView):
    model = Plan
    template_name = 'details/plan_detail.html'

    def get(self, request, *args, **kwargs):
        usuario = request.user
        plan = self.get_object()
        usuario_plan = plan.empresa.usuario

        if usuario != usuario_plan:
            return HttpResponse(status=401, content="Voce não tem acesso a essa conta")
        return super().get(self, request, *args, **kwargs)


class PhoneList(ListView):
    model = Phone
    template_name = 'partials/phone.html'
    paginate_by = 3

templates/create.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maimum-scale=1.0, minimum-scale=1.0>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Adcionando Clientes </title>
</head>
<body>

<h1>Cadastro de Clientes</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar" >
    <input type="reset" value="Cancelar" onclick="location.href = '{% url 'class:urls' %}'">


</form>
</body>

</html>

templates/home.html
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>
<body>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

</body>

{% block content %}

    <div class=""card">
        <div class="="card-body">
            <h4>REGISTROS</h4>
            <hr>
            <a class="btn btn-sucess" href="{% url 'abra'%}">Adicionar</a>
            <table class="table table-striped">

                    <tr>
                        <th>titulo</th>
                        <th>descricao</th>
                        <th>data_evento</th>
                        <th>salario</th>
                        <th>habilitado</th>
                        <th>data_criacao</th>
                        <th>usuario</th>
                        <th>ACOES</th>
                    </tr>

                    {% for evento in page_obj %}
                         <tr>
                            <td>{{ evento.titulo }}</td>
                            <td>{{ evento.descricao }}</td>
                            <td>{{ evento.data_evento }}</td>
                            <td>{{ evento.salario }}</td>
                            <td>{{ evento.habilitado }}</td>
                            <td>{{ evento.data_criacao }}</td>
                            <td>{{ evento.usuario }}</td>
                            <td>
                                <a href="{%url 'update_evento' pk=evento.pk %}" class="btn btn-warning">Editar</a>
                                <a href="{%url 'delete_evento' pk=evento.pk %}" class="btn btn-danger">Excluir</a>
                                <a href="{%url 'visualizar' pk=evento.pk %}" class="btn btn-info">Visualizar</a>
                            </td>
                        </tr>
                    {% endfor %}

{% endblock%}

            </table>
{% include 'pagination.html'  %}
        </div>
    </div>

templates/index.html
{% extends 'home.html' %}

{%block content %}
  <div class=card">
    <div class="card-body">
      <h4>{{titulo_da_pagina}}</h4>
      <hr>
      <form method ="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-sucess" href="{% url 'abra'%}">{{nome_botao}}</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primeiro</a>
            <a href="?page={{ page_obj.previous_page_number }}">Proximo</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">last</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">ultimo &raquo;</a>
        {% endif %}
    </span>
</div>

templates/preview.html
<!DOCTYPE html>
<html lang="pt-br"
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

</body>

{% block content %}

    <div class=""card">
        <div class="="card-body">
            <h4>REGISTROS</h4>
            <hr>
            <a class="btn btn-sucess" href="{% url 'abra'%}">Adicionar</a>



                         
                            <p>{{ evento.titulo }}</p>
                            <p>{{ evento.descricao }}</p>
                            <p>{{ evento.data_evento }}</p>
                            <p>{{ evento.salario }}</p>
                            <p>{{ evento.habilitado }}</p>
                            <p>{{ evento.data_criacao }}</p>
                            <p>{{ evento.usuario }}</p>
                            <p>
                                <a href="{%url 'update_evento' pk=evento.pk %}" class="btn btn-warnig">Editar</a>
                            </p>



{% endblock%}


        </div>
    </div>